on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: HatsuneMiku3939/direnv-action@v1

      - run: bun install

      - run: tsc

      - run: biome check --error-on-warnings

      - run: bun test
